apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: application2
          image: prat21/app2
